### ISSUE TITLE
Missing links mentioned in the document.

### ISSUE THREAD

**Issue by sh0kunin** [input-output-hk/Alonzo-testnet#10]
Could you please add the links mentioned in this exercise.
https://github.com/input-output-hk/Alonzo-testnet/blob/main/Alonzo-exercises/1_Alonzo-blue-exercise-1.md

 - Where to find the "Briefing Meeting" - Attend the Alonzo Testnet Briefing Meeting or Read the Testnet Briefing Notes.
 - Discord server mentioned here - Register yourself on Discord and join the designated channel.

**Comment by kevinhammond** [comment]
The briefing meeting and discord server are managed by the Comms. team - for Alonzo Blue they are invitation-only and limited in numbers.  We will gradually open up as we go to White and will provide links as appropriate.

**Comment by kevinhammond** [comment]
The links are being revised as the documentation is put online. @nahern will confirm and close this when she is done

**Comment by kevinhammond** [comment]
The missing links have been updated as far as we can.  The Briefing notes and Discord server are still restricted.  I will close this for now and we will add them when we fully open Alonzo White (the notes cover e.g. conduct on the testnet).  You can follow along on your own private cluster, of course.
