### ISSUE TITLE
mistake in Exercise3 Solution + some improvement.

### ISSUE THREAD

**Issue by lsmor** [input-output-hk/Alonzo-testnet#15]
In part one of the solution. When creating a `--mary-era` transaction, it uses the option `--protocol-params-file` which is not available for mary.

Also, is isn't clear where the `pparams.json` comes from. It'd be nice to have a line at the begining like:

`cardano-cli query protocol-parameters --testnet-magic 5 > pparams.json`

**Comment by kevinhammond** [comment]
Fixed - thank you!
