### ISSUE TITLE
Solution described in e3SampleSolution.md does not appear to work

### ISSUE THREAD

**Issue by savaki** [input-output-hk/Alonzo-testnet#17]
Using cardano-node 1.27.0 and a private testnet, I tried to reproduce the Sample solutions for exercise 3. When attempting to follow the spend step described here,

```
cardano-cli transaction build-raw \
--alonzo-era \
--fee 801000000 \
--tx-in fb169b24bbf66e9a1f779ab87fef63321a616d64e69e5e0206a6b8e8af4c7802#0 \
--tx-in-script-file untyped-always-succeeds-txin.plutus \
--tx-in-datum-value $(cat random_datum.txt) \
--tx-in-redeemer-value $(cat random_datum.txt) \
--tx-in-execution-units "(200000000,200000000)" \
--tx-in-collateral 3064e641ab188863eb3ec7755d1c06ba4c95b3db5575a87998c95c7c8053430a#1 \
--tx-out addr_test1qzsdrv4juj5hmc3dqeq9wc7kpjwmu69zwjz9j29m3l88m26hdfyr7r54f67e7c9de70ld7gzfwmhqpudvkyyvkse2gmq0cvrdj+9199000000 \
--protocol-params-file pparams.json\
--out-file tx.raw
```

the transaction always fails resulting in the loss of collateral contained in`3064e641ab188863eb3ec7755d1c06ba4c95b3db5575a87998c95c7c8053430a#1`.

I've built a number of different private alonzo testnets using `cardano-node/scripts/byron-to-alonzo/mkfiles.sh` with a parameter of `alonzo` to generate the configuration.  I've tried both with tx fees set to 0 and with tx fees set to what they are on mainnet and every attempt has failed in the same way.  The uxto with the contract attached appears un-spendable.

```
ubuntu@ip-10-0-104-12:~/scripts$ cardano-cli query utxo --cardano-mode --testnet-magic 42 --whole-utxo
                           TxHash                                 TxIx        Amount
--------------------------------------------------------------------------------------
65ab3fd095876def5b9c772aec4821d6a183e7b685d1f6f0b993dba95405b801     0        5010000000 lovelace + TxOutDatumHashNone
b1db7cf043d1277fe891ffb74c2ae68bbc104e695f0cc9139d1688a70c1bd3e5     3        10000000000 lovelace + TxOutDatumHashNone
b1db7cf043d1277fe891ffb74c2ae68bbc104e695f0cc9139d1688a70c1bd3e5     4        10000000000 lovelace + TxOutDatumHashNone
b1db7cf043d1277fe891ffb74c2ae68bbc104e695f0cc9139d1688a70c1bd3e5     5        10000000000 lovelace + TxOutDatumHashNone
b1db7cf043d1277fe891ffb74c2ae68bbc104e695f0cc9139d1688a70c1bd3e5     6        10000000000 lovelace + TxOutDatumHashNone
b1db7cf043d1277fe891ffb74c2ae68bbc104e695f0cc9139d1688a70c1bd3e5     7        10000000000 lovelace + TxOutDatumHashNone
b1db7cf043d1277fe891ffb74c2ae68bbc104e695f0cc9139d1688a70c1bd3e5     8        10000000000 lovelace + TxOutDatumHashNone
b1db7cf043d1277fe891ffb74c2ae68bbc104e695f0cc9139d1688a70c1bd3e5     9        10000000000 lovelace + TxOutDatumHashNone
b1db7cf043d1277fe891ffb74c2ae68bbc104e695f0cc9139d1688a70c1bd3e5    10        900000000000 lovelace + TxOutDatumHashNone
b6a6f3a8adb85f237230441fdcf472f557e384a468e525e900c83ae3cc3109b1     0        5000000000 lovelace + TxOutDatumHash ScriptDataInAlonzoEra "417069468791fe6c810d1a1ebe4ca78cf6c6983de997f86ec2470dc15bbe9d0f"
f640231da6ed61c2867f802c85584974967f2490da6b8e15c7614a819f239016     0        5010000000 lovelace + TxOutDatumHashNone
```

Any suggestions would be greatly appreciated.

**Comment by kevinhammond** [comment]
You're using the correct UTxO for the collateral, I assume?  

Are you giving sufficient fees?  You will need at least 10-20 ada for the current cost settings (this is about to be changed).

**Comment by CarlosLopezDeLara** [comment]
@savaki  since you are on a private testnet, can you please share your "maxTxExecutionUnits" from your protocol parameters?

**Comment by sundaeswapmatt** [comment]
For collateral, we've tried various combinations of things including:

- using exact collateral
- over-collateralizing
- reducing the execution-units to (0,0)
- we've also created private testnets using both no fees and fees similar to mainnet (a: 155381, b: 43)

Here's the `maxTxExecutionUnits` section from the protocol parameters:

```
    "maxTxExecutionUnits": {
        "memory": 500000000000,
        "steps": 500000000000
    },
```

Our current path of exploration is trying to rebuild `untyped-always-succeeds-txin.plutus` from scratch as we've been attempting to use the `AlwaysSucceeds.plutus` from the `Alonzo-testnet` repo.

**Comment by sundaeswapmatt** [comment]
So rebuilding `untyped-always-succeeds-txin.plutus` failed in the same way as the provided `AlwaysSucceeds.plutus`.  Also, we've gone so far as to try multiple releases of the `cardano-node` including:

- inputoutput/cardano-node:alonzo-blue2.0 docker image
- 1.27.0 linux binaries downloaded from cardano-node releases
- built from scratch version of cardano-node

```
cardano-node 1.27.0 - linux-x86_64 - ghc-8.10
git rev 2e25bee3ac2905cb768f77ff05b08b208996af6b
```

All appear to exhibit the same issue.  I admit, I could be making the same mistake over and over.  Any guidance would help.

**Comment by CarlosLopezDeLara** [comment]
> Our current path of exploration is trying to rebuild untyped-always-succeeds-txin.plutus from scratch as we've been attempting to use the AlwaysSucceeds.plutus from the Alonzo-testnet repo.

Note that solution proposed used untyped-always-succeeds-txin.plutus  NOT AlwaysSucceeds.plutus. I'll try with AlwaysSucceeds.

For the untyped-always-succeeds-txin.plutus I used
- this version https://github.com/input-output-hk/cardano-node/releases/tag/alonzo-blue2.0  
- exact collateral (see collateralPercentage in pparams)  

In our first tests execution was failing due to "maxTxExecutionUnits" being set to (1,1) but in your case it looks fine.

**Comment by sundaeswapmatt** [comment]
That did the trick.  The `untyped-always-succeeds-txin.plutus` script worked as expected!

Thank you!

Mind if I submit an update to the `Alonzo-testnet` docs to replace `AlwaysSucceeds.plutus` with `untyped-always-succeeds-txin.plutus`?

**Comment by savaki** [comment]
And for clarification, the version of `untyped-always-succeeds-txin.plutus` that worked was the tagged version.  It appears the version in master is different and we haven't tested that yet.

**Comment by CarlosLopezDeLara** [comment]
> Mind if I submit an update to the Alonzo-testnet docs to replace AlwaysSucceeds.plutus with untyped-always-succeeds-txin.plutus?

Actually AlwaysSucceds is the one that we want new joiners to use. I still need to test that, but should also work.

**Comment by CarlosLopezDeLara** [comment]
Reopened. I'll leave this open until I post the solutions for ex3 with AlwaysSucceeds.pluts

**Comment by kevinhammond** [comment]
The two scripts should actually be identical, I think.  There might just be eg some versioning issues with the Plutus interpreter.
The name "AlwaysSucceeds" is better than "untyped-always-succeeds" - the code is properly typed and the types must match between the source and datums, so this is potentially confusing

**Comment by kevinhammond** [comment]
I know @CarlosLopezDeLara is working on this.  Perhaps he can provide an update.

**Comment by james-iohk** [comment]
Working solution now exists. Closing.
