### ISSUE TITLE
Add examples of automated test coverage to the solutions

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/Alonzo-testnet#26]
In the pioneer program we were able to run our scripts in the playground and later learned about automated test coverage. It be nice to have something similar for the current exercises too. Especially now, where there is so little feedback (i.e. not even logging) from on-chain validation.

**Comment by kevinhammond** [comment]
We are working on improved on-chain logging (specifically for validation failures).   Keep an eye on the node PRs for this.

There is automated test coverage within the node (using Quickcheck/Hedgehog), but that's not at the Plutus Script level so would not be useful to you.   For Alonzo White, you would really need to do this within shell scripts or some other wraper.  Community contributions welcomed, for this, of course!

In the slightly longer term, we will have Plutus Application Backend integration with the node, so you will be able to use that to check your solutions as with the Playground (including transaction submission to Testnets).  You should also be able to embed your solutions within the Playground for mock chain execution now, I imagine, but you won't yet get feedback about actual on-chain execution (the point of the Testnet).

**Comment by james-iohk** [comment]
Hi @tdiesler. Are you talking about the when Lars taught the Pioneers about test modules such as [Test.hs](https://github.com/input-output-hk/plutus/blob/master/plutus-contract/src/Plutus/Contract/Test.hs) and [ContractModel.hs](https://github.com/input-output-hk/plutus/blob/master/plutus-contract/src/Plutus/Contract/Test/ContractModel.hs)?
Seeing as this is entirely "offchain" activity this may be beyond scope for what we want to achieve here with Alonzo-testnet.
There is the upcoming lecture on this in the 2nd Pioneers cohort (probably lecture 8 again), and there are some examples of this in the plutus repo to refer to: https://github.com/input-output-hk/plutus/tree/master/plutus-use-cases/test/Spec

**Comment by kevinhammond** [comment]
Maybe transfer this to the Plutus Pioneers repository for them to action?

**Comment by kevinhammond** [comment]
I will close this now.  @tdiesler - can you raise it in the Plutus Pioneers repository instead, please (you should be able to copt what you have written).
