### ISSUE TITLE
Alonzo white sync error 

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/Alonzo-testnet#36]
I have started node 
cardano-node run \
		--topology alonzo-white-topology.json \
		--database-path db \
		--socket-path node.socket \
		--port 3001 \
		--config alonzo-white-config.json
 
it syncs successfully until
{
    "epoch": 97,
    "hash": "73162004bd3dbb779a7eaa74925fcd2b049c0c7327eaec0ce70ef3116cc9fd8c",
    "slot": 691960,
    "block": 34012,
    "era": "Alonzo",
    "syncProgress": "26.49"
}

Error:
[WS:cardano.node.ChainDB:Error:21]  [2021-08-06 07:09:53.33 UTC] Invalid block ddd1200a49f0a24d1ba00ce7244eacfbd9422cfdbe6a16b461cdc5a081b3c130 at slot 691987: ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [TooManyExUnits (ExUnits {exUnitsMem = 15800, exUnitsSteps = 81620000}) (ExUnits {exUnitsMem = 1, exUnitsSteps = 1}),ShelleyInAlonzoPredFail (LedgersFailure (LedgerFailure (UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ExUnitsTooBigUTxO (ExUnits {exUnitsMem = 1, exUnitsSteps = 1}) (ExUnits {exUnitsMem = 15800, exUnitsSteps = 81620000}))))))),ShelleyInAlonzoPredFail (LedgersFailure (LedgerFailure (UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (InsufficientCollateral (Coin 4000000) (Coin 102635800)))))))])}))))))

**Comment by kevinhammond** [comment]
I think this was because you had built the wrong version of the node, as discussed on the discord channel?  The correct version is tagged from the Testnet page.

Generally we recommend using the pre-built docker or OS-specific versions on the Testnet to avoid possible configuration mismatches (also because the build can be complex)

**Comment by volodyad** [comment]
I have used version provided in https://hydra.iohk.io/build/6907043

**Comment by james-iohk** [comment]
@volodyad I think the correct ones to use were https://hydra.iohk.io/build/6928147/download/1/index.html

**Comment by kevinhammond** [comment]
Thanks, James
