### ISSUE TITLE
Alonzo blue sync error

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/Alonzo-testnet#37]
I have started node
cardano-node run \
	--topology alonzo-blue-topology.json \
	--database-path db \
	--socket-path node.socket \
	--port 3001 \
	--config alonzo-blue-config.json \

it syncs successfully until
{
    "epoch": 234,
    "hash": "7a1490c9b70bee0a81274393f579114b9e32ffc2358df82762a972af6c075be5",
    "slot": 1678283,
    "block": 81983,
    "era": "Alonzo",
    "syncProgress": "27.68"
}

Error:
[WS:cardano.node.DnsSubscription:Error:318] [2021-08-06 07:17:15.12 UTC] Domain: "relays.alonzo-blue.dev.cardano.org" Application Exception: 50.18.74.57:3001 DecoderFailure (BlockFetchHardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) (': * (ShelleyBlock (AlonzoEra StandardCrypto)) ('[] *))))))) ServerAgency TokStreaming) (DeserialiseFailure 1404 "expected tag")

**Comment by kevinhammond** [comment]
Alonzo Blue is no longer running.  You will need the White or Purple configuration information
