### ISSUE TITLE
Exercice 3. Lock funds forever in the plutus script

### ISSUE THREAD

**Issue by psychomb** [input-output-hk/Alonzo-testnet#5]
The order in which you specify the --tx-out flags when building the transaction matters a lot. 

````
cardano-cli transaction build-raw --alonzo-era \
--tx-in aa1d18824746b58ce4ed242211f4e785d3b97f9fe6b255de27d5c3bb1056a55b#0 \
--tx-out $changeAddress+value \
--tx-out $plutusScriptAddress+value \
--tx-out-datum-hash $hash \
--invalid-hereafter $slotHeight \
--fee value \
--out-file tx.raw
````
will succeed. However, the same transaction as written below will end up locked forever without datum associated with the newly created script utxo.

````
cardano-cli transaction build-raw --alonzo-era \
--tx-out-datum-hash $hash \
--tx-in aa1d18824746b58ce4ed242211f4e785d3b97f9fe6b255de27d5c3bb1056a55b#0 \
--tx-out $changeAddress+value \
--tx-out $plutusScriptAddress+value \
--invalid-hereafter $slotHeight \
--fee value \
--out-file tx.raw
````

My understanding from this is that the datum will go to the closest `--tx-out` when building the transaction. Is this correct ?

**Comment by psychomb** [comment]
Answer (thanks @mdebruijne): 

Order matters a lot because every UTxO can have different predicates. That's why you need to group the predicates that apply to that specific UTxO together.

If you provide a tx-in, all subsequent tx-in-... arguments apply to the UTxO referenced by that tx-in until the next tx-in or tx-out.

If you provide a tx-out, all subsequent tx-out-... arguments apply to the UTxO referenced by that tx-out until the next tx-out or tx-in.

**Comment by DanTup** [comment]
Perhaps it should be an error to supply a `--tx-out-datum-hash` without a `--tx-out` before it?

**Comment by dcoutts** [comment]
Indeed it does. Here's the relevant output from the `cardano-cli transaction build-raw --help`:
```
[--tx-out ADDRESS VALUE [--tx-out-datum-hash HASH]] 
```
So yes, you can have any number of `--tx-out` and after each one an optional `--tx-out-datum-hash`.

(Sadly the [] notation does not distinguish between zero-or-one and zero-or-more.)

And if one looks at the full `--help` output, you'll see the same applies to the other script-related flags. This is pretty much unavoidable for the CLI given the complicated structure of transaction inputs etc, at least if we stick to the style of being able to build the whole tx body in one go.

**Comment by dcoutts** [comment]
We should perhaps look at whether we can disallow reordering since for these ones it could cause confusion. I don't know for sure if `optparse-applicative` would let us ban reordering on some but not all flags.

**Comment by CarlosLopezDeLara** [comment]
@dcoutts comment above solves the question.
